export const COURSES = [
  'Digital Marketing',
  'Graphic Designing',
  'Video Editing',
  'Web Development',
  'UI/UX Design',
  'Blender',
  'Tally with GST',
  'Power BI',
  'Artificial Intelligence',
  'Advance Excel',
  'VBA Programming',
  'AutoCAD',
  '3DS Max',
  'SolidWorks',
  'Interior Designing',
  'Revit Architecture',
  'SketchUp',
  'Architecture Designing',
  'V-Ray',
  'Mechanical CADD',
  'ArtCAM',
  'C Language',
  'C++',
  'Python',
  'Programming',
  'Android Development',
  'RS-CIT',
  'PGDCA',
  'CCC',
  'COPA'
];
